### ISSUE TITLE
Uniqueness of the tool?

### ISSUE THREAD

**Issue by kcnaiamh** [dievus/geeMailUserFinder#1]
There is already many tools like this
- [Verify email](https://verify-email.org/)
- [Verify email address](https://www.verifyemailaddress.org/)

which are more versatile. Not gmail specific.

What is the uniqueness of this tool?

**Comment by dievus** [comment]
When I write a tool, it isn't for anyone else. I write them for myself, either to solve an immediate problem or to learn something. That I decide to share them with the world is out of kindness, and I really could care a less what else is available. 

That said, this tool, along with my Oh365UserFinder tool, both exist for very specific tasks appropriate for my work as a penetration tester. Neither of those websites says anything of much value about the email addresses themselves. The one simply says ok, while the other one may respond back with something regarding a connection to an email server. I can tell you with all certainty, however, that it is incredibly basic. As an example, those sites do not differentiate between Azure with GCP integration, which shows an immediate shortcoming. If something like DesktopSSO is enabled on the Azure side with the GCP connector, you will not be able to determine if the account is even real or not. That is why I wrote this tool specifically.

In the end, I don't care about uniqueness, how many stars I get, or anything else. Why you would even decide to post this as an issue is completely beyond me, but I hope it answers your question.
